prompt Dropping package ExcelTable ...
drop package ExcelTable;

prompt Dropping type ExcelTableImpl ...
drop type ExcelTableImpl;

prompt Dropping package XUTL_FLATFILE ...
drop package xutl_flatfile;

prompt Dropping package XUTL_XLSB ...
drop package xutl_xlsb;

prompt Dropping package XUTL_XLS ...
drop package xutl_xls;

prompt Dropping type ExcelTableSheetList ...
drop type ExcelTableSheetList;

prompt Dropping type ExcelTableCellList ...
drop type ExcelTableCellList;

prompt Dropping type ExcelTableCell ...
drop type ExcelTableCell;

prompt Dropping package XUTL_OFFCRYPTO ...
drop package xutl_offcrypto;

prompt Dropping package XUTL_CDF ...
drop package xutl_cdf;
